frr version 10.3
frr defaults traditional
hostname frr2
log syslog informational
service integrated-vtysh-config
!
router bgp 65020
 no bgp ebgp-requires-policy
 bgp bestpath as-path multipath-relax
 neighbor eth1 interface remote-as 65001
 neighbor eth1 bfd
 neighbor eth2 interface remote-as 65002
 neighbor eth2 bfd
 !
 address-family ipv4 unicast
  maximum-paths 4
  neighbor eth1 activate
  neighbor eth2 activate
  network 10.65.20.0/24
 exit-address-family
 !
 address-family ipv6 unicast
  maximum-paths 4
  neighbor eth1 activate
  neighbor eth2 activate
 exit-address-family
!
