frr version 10.3
frr defaults traditional
hostname ${DEVICE_NAME}
log syslog informational
service integrated-vtysh-config
!
router bgp ${AS}
 no bgp ebgp-requires-policy
 neighbor ${PEER_INTERFACE} interface remote-as ${PEER_REMOTE_AS}
 neighbor ${PEER_INTERFACE} bfd
 !
 address-family ipv4 unicast
  neighbor ${PEER_INTERFACE} activate
  network ${ANNOUNCED_PREFIX}
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor ${PEER_INTERFACE} activate
 exit-address-family
!
